Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -13,25 +13,20 @@ jobs:
       contents: read
 
     steps:
-      # 소스 코드 체크아웃
       - uses: actions/checkout@v4
 
-      # JDK 설정
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      # Gradle 설정
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4.0.0
 
-      # Gradle Wrapper 실행 권한 부여
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
-      # Spring Boot 애플리케이션 빌드
       - name: Build with Gradle Wrapper
         env:
           SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
@@ -52,18 +47,15 @@ jobs:
           GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
         run: ./gradlew build -x test
 
-      # Docker 이미지 빌드
       - name: Build Docker Image
-        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .
+        run: docker build --cache-from ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .
 
-      # DockerHub 로그인
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      # DockerHub로 이미지 푸시
       - name: Push Docker Image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test
 
@@ -72,11 +64,13 @@ jobs:
     runs-on: self-hosted
 
     steps:
-      # EC2에서 Docker 이미지 가져오기
       - name: Pull Docker Image
-        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test
+        run: |
+          if ! sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test; then
+            echo "Docker pull failed. Ensure the image exists in DockerHub."
+            exit 1
+          fi
 
-      # 기존 컨테이너 중지 및 삭제
       - name: Stop and Remove Existing Container
         run: |
           if [ $(sudo docker ps -a -q -f name=spring-cicd-test) ]; then
@@ -84,10 +78,10 @@ jobs:
             sudo docker rm spring-cicd-test
           fi
 
-      # 새 컨테이너 실행
       - name: Run New Docker Container
-        run: sudo docker run --rm -d -p 80:8080 --name spring-cicd-test ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test
+        run: sudo docker run -d -p 80:8080 --name spring-cicd-test ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test
 
-      # 불필요한 Docker 이미지 정리
       - name: Clean Up Docker
-        run: sudo docker system prune -f
+        run: |
+          sudo docker image prune -f
+          sudo docker container prune -f
